import MeasureTheory.Measure.LebesgueDoc.Support

set_option verso.exampleProject "."
set_option verso.exampleModule "MeasureTheory.Lean.Measures.Bind"
lebesgue_doc_module MeasureTheory.Lean.Measures.Bind
open Verso Genre Manual

set_option linter.style.setOption false
set_option maxHeartbeats 2000000
set_option linter.style.setOption true

#doc (Manual) "Kernel Integration" =>

%%%
file := "Kernel"
tag := "kernel"
%%%

:::lebesgueDocSetup
:::

:::localizedPart (ja := "カーネル積分")
:::

:::::definitionBox
::::localized
For a measurable space $`X`, we regard $`\Measure(X)` as a measurable space
by equipping it with the sigma-algebra generated by the sets
$$`
  \left\{
    \mu \in \Measure(X) \mid \mu(A) \in B
  \right\},`
where $`A \subseteq X` is measurable and $`B \subseteq [0,\infty]` is measurable.
In particular, for any measurable set $`A \subseteq X`, the evaluation map
$$`
  \mu \mapsto \mu(A)`
is measurable.
:::locale "ja"
可測空間 $`X` に対して、$`\Measure(X)` に
$$`
  \left\{
    \mu \in \Measure(X) \mid \mu(A) \in B
  \right\}
`
で生成される σ-代数を入れることで、$`\Measure(X)` を可測空間とみなす。
ただし $`A \subseteq X` は可測、$`B \subseteq [0,\infty]` は可測とする。
特に、任意の可測集合 $`A \subseteq X` に対して評価写像
$$`
  \mu \mapsto \mu(A)
`
は可測である。
:::
::::
:::::

```leanDecl
MTI.Measure.MeasurableGen
MTI.Measure.instMeasurableSpace
MTI.Measure.measurable_coe
```

:::::lemmaBox
::::localized
To prove that a map $`\mu : X \to \Measure(Y)` is measurable, it suffices to show that
for any measurable set $`A \subseteq Y`, the scalar-valued map
$$`
  x \mapsto \mu(x)(A)`
is measurable.
:::locale "ja"
写像 $`\mu : X \to \Measure(Y)` が可測であることを示すには、任意の可測集合
$`A \subseteq Y` に対してスカラー値写像
$$`
  x \mapsto \mu(x)(A)
`
が可測であることを示せば十分である。
:::
::::
:::::

```leanDecl
MTI.measurable_of_measurable_coe
```

:::::lemmaBox
::::localized
If $`f : X \to [0,\infty]` is measurable, then the map
$$`
  \mu \mapsto \underline{\int}_{x \in X} f(x)\,d\mu`
from $`\Measure(X)` to $`[0,\infty]` is measurable.
:::locale "ja"
$`f : X \to [0,\infty]` が可測ならば、写像
$$`
  \mu \mapsto \underline{\int}_{x \in X} f(x)\,d\mu
`
は $`\Measure(X)` から $`[0,\infty]` への可測写像である。
:::
::::
:::::

```leanDecl
MTI.Measure.measurable_lintegral
```

:::::definitionBox
::::localized
Let $`X` and $`Y` be measurable spaces, and let
$`\nu : X \to \Measure(Y)` be a measurable map.
For a measure $`\mu` on $`X`, we define a measure
$`\mathcal{K}_{\nu}(\mu)` on $`Y` by
$$`
  \mathcal{K}_{\nu}(\mu)(A)
    \coloneqq
  \underline{\int}_{x \in X} \nu_x(A)\,d\mu`
for measurable sets $`A \subseteq Y`.
:::locale "ja"
$`X` と $`Y` を可測空間とし、
$`\nu : X \to \Measure(Y)` を可測写像とする。
$`X` 上の測度 $`\mu` に対して、$`Y` 上の測度
$`\mathcal{K}_{\nu}(\mu)` を、可測集合 $`A \subseteq Y` に対して
$$`
  \mathcal{K}_{\nu}(\mu)(A)
    \coloneqq
  \underline{\int}_{x \in X} \nu_x(A)\,d\mu
`
で定める。
:::
::::
:::::

```leanDecl
MTI.Measure.bind
MTI.Measure.bind_apply
```

:::::lemmaBox
::::localized
Let $`f : Y \to [0,\infty]` be measurable.
Then
$$`
  \underline{\int}_{y \in Y} f(y)\,d(\mathcal{K}_{\nu}(\mu))
    =
  \underline{\int}_{x \in X}
    \underline{\int}_{y \in Y} f(y)\,d\nu_x\,d\mu.`
:::locale "ja"
$`f : Y \to [0,\infty]` を可測とする。
このとき
$$`
  \underline{\int}_{y \in Y} f(y)\,d(\mathcal{K}_{\nu}(\mu))
    =
  \underline{\int}_{x \in X}
    \underline{\int}_{y \in Y} f(y)\,d\nu_x\,d\mu.
`
が成り立つ。
:::
::::
:::::

```leanDecl
MTI.lintegral_bind
```
