import MeasureTheory.Measure.LebesgueDoc.Support

set_option verso.exampleProject "."
set_option verso.exampleModule "MeasureTheory.Lean.Dynkin"
lebesgue_doc_module MeasureTheory.Lean.Dynkin
lebesgue_doc_module MeasureTheory.Lean.MeasurableSpace
open Verso Genre Manual

set_option linter.style.setOption false
set_option maxHeartbeats 2000000
set_option linter.style.setOption true

#doc (Manual) "Measurable Space Generated by a Set of Sets" =>

%%%
file := "Measurable-Space-Generated-by-a-Set-of-Sets"
tag := "measurable-space-generated-by-a-set-of-sets"
%%%

:::lebesgueDocSetup
:::

:::localizedPart (ja := "集合族が生成する可測空間")
:::

:::::definitionBox
::::localized
Let $`X` be a set,
and let $`\mathcal{F} \subseteq \mathcal{P}(X)`.
We inductively define the sigma-algebra $`\gen (\mathcal{F})` on $`X`,
called the _sigma-algebra generated by $`\mathcal{F}`_,
as follows:

1. For any $`A \in \mathcal{F}`, we have $`A \in \gen (\mathcal{F})`.
2. $`\emptyset \in \gen (\mathcal{F})`.
3. For any $`A \in \gen (\mathcal{F})`, we have $`A^c \in \gen (\mathcal{F})`.
4. For any sequence $`A_0, A_1, \dots \in \gen (\mathcal{F})`,
   we have $`\bigcup_{n \in \mathbb{N}} A_n \in \gen (\mathcal{F})`.
:::locale "ja"
$`X` を集合とし、$`\mathcal{F} \subseteq \mathcal{P}(X)` とする。
$`X` 上の σ-代数 $`\gen (\mathcal{F})` を、_$`\mathcal{F}` が生成する σ-代数_ と呼び、次で帰納的に定める。

1. 任意の $`A \in \mathcal{F}` に対して $`A \in \gen (\mathcal{F})` である。
2. $`\emptyset \in \gen (\mathcal{F})` である。
3. 任意の $`A \in \gen (\mathcal{F})` に対して $`A^c \in \gen (\mathcal{F})` である。
4. 任意の列 $`A_0, A_1, \dots \in \gen (\mathcal{F})` に対して
   $`\bigcup_{n \in \mathbb{N}} A_n \in \gen (\mathcal{F})` である。
:::
::::
:::::

```leanDecl
MTI.GenerateMeasurable
MTI.generateFrom
```

:::::lemmaBox "Induction Principle for Measurable Sets" (ja := "可測集合の帰納法")
::::localized
Let $`X` be a measurable space,
and let $`\mathcal{F} \subseteq \mathcal{P}(X)`.
Suppose that $`\mathcal{M}(X) = \gen (\mathcal{F})`.
Let $`P(A)` be a property on measurable sets $`A \subseteq X`.
Suppose that the following conditions hold:

1. For any $`A \in \mathcal{F}`, we have $`P(A)`.
2. We have $`P(\emptyset)`.
3. For any measurable set $`A \subseteq X`, we have $`P(A)` implies $`P(A^c)`.
4. For any sequence of measurable sets $`A_0, A_1, \dots \subseteq X`,
   we have $`\forall n \in \mathbb{N}, P(A_n)` implies
   $`P\left(\bigcup_{n \in \mathbb{N}} A_n\right)`.

Then any measurable set $`A \subseteq X` satisfies $`P(A)`.
:::locale "ja"
$`X` を可測空間とし、$`\mathcal{F} \subseteq \mathcal{P}(X)` とする。
$`\mathcal{M}(X) = \gen (\mathcal{F})` と仮定する。
可測集合 $`A \subseteq X` に関する性質 $`P(A)` を考える。
次を仮定する。

1. 任意の $`A \in \mathcal{F}` に対して $`P(A)` が成り立つ。
2. $`P(\emptyset)` が成り立つ。
3. 任意の可測集合 $`A \subseteq X` に対して、$`P(A)` ならば $`P(A^c)` である。
4. 任意の可測集合列 $`A_0, A_1, \dots \subseteq X` に対して、
   $`\forall n \in \mathbb{N}, P(A_n)` ならば
   $`P\left(\bigcup_{n \in \mathbb{N}} A_n\right)` である。

このとき任意の可測集合 $`A \subseteq X` は $`P(A)` を満たす。
:::
::::
:::::

```leanDecl
MTI.generateFrom_induction
```

:::::definitionBox
::::localized
Let $`X` be a set, and let $`\mathcal{F} \subseteq \mathcal{P}(X)`.
We inductively define the set of sets
$`\dgen (\mathcal{F}) \subseteq \mathcal{P}(X)`,
called the _Dynkin system generated by $`\mathcal{F}`_,
as follows:

1. For any $`A \in \mathcal{F}`, we have $`A \in \dgen (\mathcal{F})`.
2. $`\emptyset \in \dgen (\mathcal{F})`.
3. For any $`A \in \dgen (\mathcal{F})`, we have $`A^c \in \dgen (\mathcal{F})`.
4. For any sequence $`A_0, A_1, \dots \in \dgen (\mathcal{F})` such that
   $`A_i \cap A_j = \emptyset` if $`i \neq j`,
   we have $`\bigcup_{n \in \mathbb{N}} A_n \in \dgen (\mathcal{F})`.
:::locale "ja"
$`X` を集合とし、$`\mathcal{F} \subseteq \mathcal{P}(X)` とする。
集合族
$`\dgen (\mathcal{F}) \subseteq \mathcal{P}(X)` を _$`\mathcal{F}` が生成するディンキン系_ と呼び、次で帰納的に定める。

1. 任意の $`A \in \mathcal{F}` に対して $`A \in \dgen (\mathcal{F})` である。
2. $`\emptyset \in \dgen (\mathcal{F})` である。
3. 任意の $`A \in \dgen (\mathcal{F})` に対して $`A^c \in \dgen (\mathcal{F})` である。
4. 任意の列 $`A_0, A_1, \dots \in \dgen (\mathcal{F})` で、$`i \neq j` ならば
   $`A_i \cap A_j = \emptyset` を満たすものに対して、
   $`\bigcup_{n \in \mathbb{N}} A_n \in \dgen (\mathcal{F})` である。
:::
::::
:::::

```leanDecl
MTI.GenDynkin
```

:::::lemmaBox "Dynkin's π-λ Theorem" (ja := "ディンキンの π-λ 定理")
::::localized
Let $`X` be a measurable space, and let $`\mathcal{F} \subseteq \mathcal{P}(X)`.
Suppose that $`\mathcal{M}(X) = \gen (\mathcal{F})`.
Suppose that for any $`A, B \in \mathcal{F}`, we have $`A \cap B \in \mathcal{F}`.
Then for any $`A \subseteq X`,
$`A` is measurable if and only if $`A \in \dgen (\mathcal{F})`.
:::locale "ja"
$`X` を可測空間とし、$`\mathcal{F} \subseteq \mathcal{P}(X)` とする。
$`\mathcal{M}(X) = \gen (\mathcal{F})` と仮定する。
さらに任意の $`A, B \in \mathcal{F}` に対して $`A \cap B \in \mathcal{F}` が成り立つとする。
このとき任意の $`A \subseteq X` について、
$`A` が可測であることと $`A \in \dgen (\mathcal{F})` であることは同値である。
:::
::::
:::::

```leanDecl
MTI.genDynkin_inter_compl_right
MTI.genDynkin_inter_compl_left
MTI.genDynkin_inter
MTI.measurableSet_iff_mem_genDynkin
```

:::::lemmaBox "Induction Principle for Measurable Sets after π-λ" (ja := "π-λ 定理を用いた可測集合の帰納法")
::::localized
Let $`X` be a measurable space,
and let $`\mathcal{F} \subseteq \mathcal{P}(X)`.
Suppose that $`\mathcal{M}(X) = \gen (\mathcal{F})`.
Suppose that for any $`A, B \in \mathcal{F}`, we have $`A \cap B \in \mathcal{F}`.
Let $`P(A)` be a property on measurable sets $`A \subseteq X`.
Suppose that the following conditions hold:

1. For any $`A \in \mathcal{F}`, we have $`P(A)`.
2. We have $`P(\emptyset)`.
3. For any measurable set $`A \subseteq X`, we have $`P(A)` implies $`P(A^c)`.
4. For any sequence of measurable sets $`A_0, A_1, \dots \subseteq X`
   such that $`A_i \cap A_j = \emptyset` if $`i \neq j`,
   we have $`\forall n \in \mathbb{N}, P(A_n)` implies
   $`P\left(\bigcup_{n \in \mathbb{N}} A_n\right)`.

Then any measurable set $`A \subseteq X` satisfies $`P(A)`.
:::locale "ja"
$`X` を可測空間とし、$`\mathcal{F} \subseteq \mathcal{P}(X)` とする。
$`\mathcal{M}(X) = \gen (\mathcal{F})` と仮定する。
さらに任意の $`A, B \in \mathcal{F}` に対して $`A \cap B \in \mathcal{F}` が成り立つとする。
可測集合 $`A \subseteq X` に関する性質 $`P(A)` を考える。
次を仮定する。

1. 任意の $`A \in \mathcal{F}` に対して $`P(A)` が成り立つ。
2. $`P(\emptyset)` が成り立つ。
3. 任意の可測集合 $`A \subseteq X` に対して、$`P(A)` ならば $`P(A^c)` である。
4. 任意の可測集合列 $`A_0, A_1, \dots \subseteq X` で、$`i \neq j` ならば
   $`A_i \cap A_j = \emptyset` を満たすものに対して、
   $`\forall n \in \mathbb{N}, P(A_n)` ならば
   $`P\left(\bigcup_{n \in \mathbb{N}} A_n\right)` である。

このとき任意の可測集合 $`A \subseteq X` は $`P(A)` を満たす。
:::
::::
:::::

```leanDecl
MTI.induction_on_inter
```
