import MeasureTheory.Measure.LebesgueDoc.Support

set_option verso.exampleProject "."
set_option verso.exampleModule "MeasureTheory.Lean.Prod"
lebesgue_doc_module MeasureTheory.Lean.Prod
lebesgue_doc_module Mathlib.MeasureTheory.Measure.Typeclasses.Finite
lebesgue_doc_module Mathlib.MeasureTheory.Measure.Typeclasses.SFinite
open Verso Genre Manual

set_option linter.style.setOption false
set_option maxHeartbeats 2000000
set_option linter.style.setOption true

#doc (Manual) "Product Measure" =>

%%%
file := "Product-Measure"
tag := "product-measure"
%%%

:::lebesgueDocSetup
:::

:::localizedPart (ja := "直積測度")
:::

:::::definitionBox
::::localized
Let $`X` and $`Y` be measurable spaces.
We regard the set $`X \times Y` as a _measurable space_
by equipping it with the sigma-algebra generated by the set
$$`
  \{ A \times B \mid \text{$A \subseteq X$ and $B \subseteq Y$ are measurable} \}.`
:::locale "ja"
$`X` と $`Y` を可測空間とする。
集合 $`X \times Y` に
$$`
  \{ A \times B \mid \text{$A \subseteq X$ と $B \subseteq Y$ は可測} \}
`
が生成する σ-代数を入れることで、$`X \times Y` を _可測空間_ とみなす。
:::
::::
:::::

```leanDecl
MTI.GenProd
MTI.instMeasurableSpaceProd
MTI.MeasurableSet.sProd
MTI.measurable_fst
MTI.measurable_snd
```

:::::definitionBox
::::localized
Let $`X` be a measurable space.
A measure $`\mu` on $`X` is said to be _finite_ if
$`\mu (X) < \infty`.
:::locale "ja"
$`X` を可測空間とする。
$`X` 上の測度 $`\mu` が _有限_ であるとは、$`\mu(X) < \infty` が成り立つことをいう。
:::
::::
:::::

```leanDecl
MeasureTheory.IsFiniteMeasure
```

:::::definitionBox
::::localized
Let $`X` be a measurable space,
and let $`\mu` be a measure on $`X`.
We say that $`\mu` is _S-finite_ if
there exists a sequence
$`\nu : \mathbb{N} \to \Measure (X)` of measures on $`X` such that
$`\nu_n` is finite for any $`n \in \mathbb{N}`
and $`\mu = \sum_{n \in \mathbb{N}} \nu_n`.
:::locale "ja"
$`X` を可測空間とし、$`\mu` を $`X` 上の測度とする。
$`\mu` が _S-有限_ であるとは、$`X` 上の測度の列
$`\nu : \mathbb{N} \to \Measure (X)` が存在して、任意の $`n \in \mathbb{N}` に対して
$`\nu_n` が有限であり、かつ $`\mu = \sum_{n \in \mathbb{N}} \nu_n` が成り立つことをいう。
:::
::::
:::::

```leanDecl
MeasureTheory.SFinite
```

:::::lemmaBox
::::localized
Let $`X` and $`Y` be measurable spaces.
Let $`\mu` be a measure on $`X`,
and let $`\nu` be a measure on $`Y`.
Suppose that $`\nu` is S-finite.
Then for any measurable set $`A \subseteq X \times Y`,
the function $`f : X \to [0, \infty]` defined by
$`f (x) \coloneqq \nu (\{ y \in Y \mid (x,y) \in A \})`
is measurable.
:::locale "ja"
$`X` と $`Y` を可測空間とする。
$`\mu` を $`X` 上の測度、$`\nu` を $`Y` 上の測度とし、$`\nu` は S-有限であると仮定する。
このとき任意の可測集合 $`A \subseteq X \times Y` に対して、
$`f : X \to [0, \infty]` を
$`f (x) \coloneqq \nu (\{ y \in Y \mid (x,y) \in A \})`
で定めると、$`f` は可測である。
:::
::::
:::::

```leanDecl
MTI.measurable_measure_prodMk_left_finite
MTI.measurable_measure_prodMk_left
```

:::::definitionBox
::::localized
Let $`X` and $`Y` be measurable spaces.
Let $`\mu` be a measure on $`X`,
and let $`\nu` be a measure on $`Y`.
Suppose that $`\nu` is S-finite.
We define the _product measure_ $`\mu \times \nu` on $`X \times Y` by
$$`
  (\mu \times \nu)(A)
    \coloneqq
  \underline{\int}_{x \in X} \nu (\{ y \in Y \mid (x,y) \in A \})\,d\mu
`
for any measurable set $`A \subseteq X \times Y`.
:::locale "ja"
$`X` と $`Y` を可測空間とし、$`\mu` を $`X` 上の測度、$`\nu` を $`Y` 上の測度とする。
$`\nu` は S-有限であると仮定する。
このとき $`X \times Y` 上の _直積測度_ $`\mu \times \nu` を、任意の可測集合
$`A \subseteq X \times Y` に対して
$$`
  (\mu \times \nu)(A)
    \coloneqq
  \underline{\int}_{x \in X} \nu (\{ y \in Y \mid (x,y) \in A \})\,d\mu
`
で定める。
:::
::::
:::::

```leanDecl
MTI.Measure.prod
MTI.prod_apply
```

:::::lemmaBox
::::localized
Suppose that $`\nu` is S-finite.
Then for any measurable sets $`A \subseteq X` and $`B \subseteq Y`,
we have
$$`
  (\mu \times \nu) (A \times B) = \mu (A) \cdot \nu (B).`
:::locale "ja"
$`\nu` が S-有限であるとする。
このとき任意の可測集合 $`A \subseteq X` と $`B \subseteq Y` に対して
$$`
  (\mu \times \nu) (A \times B) = \mu (A) \cdot \nu (B)
`
が成り立つ。
:::
::::
:::::

```leanDecl
MTI.prod_prod
```

:::::theoremBox "Tonelli's Theorem" (ja := "トネリの定理")
::::localized
Let $`X` and $`Y` be measurable spaces.
Let $`\mu` be a measure on $`X`,
and let $`\nu` be a measure on $`Y`.
Suppose that $`\mu` and $`\nu` are S-finite.
Let $`f : X \times Y \to [0, \infty]` be a measurable function.
Then we have
$$`
  \begin{aligned}
    \underline{\int}_{(x,y) \in X \times Y} f (x,y) \, d(\mu \times \nu)
      &=
    \underline{\int}_{x \in X} \left(
      \underline{\int}_{y \in Y} f (x,y) \, d\nu
    \right) d\mu \\
      &=
    \underline{\int}_{y \in Y} \left(
      \underline{\int}_{x \in X} f (x,y) \, d\mu
    \right) d\nu.
  \end{aligned}`
:::locale "ja"
$`X` と $`Y` を可測空間とする。
$`\mu` を $`X` 上の測度、$`\nu` を $`Y` 上の測度とし、$`\mu` と $`\nu` は S-有限であると仮定する。
$`f : X \times Y \to [0, \infty]` を可測関数とする。
このとき
$$`
  \begin{aligned}
    \underline{\int}_{(x,y) \in X \times Y} f (x,y) \, d(\mu \times \nu)
      &=
    \underline{\int}_{x \in X} \left(
      \underline{\int}_{y \in Y} f (x,y) \, d\nu
    \right) d\mu \\
      &=
    \underline{\int}_{y \in Y} \left(
      \underline{\int}_{x \in X} f (x,y) \, d\mu
    \right) d\nu.
  \end{aligned}
`
が成り立つ。
:::
::::
:::::

```leanDecl
MTI.lintegral_prod
MTI.prod_swap
MTI.lintegral_prod_symm
MTI.lintegral_prod_swap'
```
